apiVersion: v1
kind: Namespace
metadata:
  name: k8sproject
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8sproject-operator
  namespace: k8sproject
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8sproject-operator
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8sproject-operator
subjects:
- kind: ServiceAccount
  name: k8sproject-operator
  namespace: k8sproject
roleRef:
  kind: ClusterRole
  name: k8sproject-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sproject-operator
  namespace: k8sproject
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      name: k8sproject-operator
  template:
    metadata:
      labels:
        name: k8sproject-operator
    spec:
      containers:
      - name: k8sproject-operator
        imagePullPolicy: Always
        image: k8sproject/px-operator:<k8sproject_operator_version_replaceme>
        command:
        - /operator
        - --verbose
        - --driver=k8sproject
        - --leader-elect=true
        env:
        - name: OPERATOR_NAME
          value: k8sproject-operator
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "name"
                    operator: In
                    values:
                    - k8sproject-operator
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: k8sproject-operator
