apiVersion: v1
kind: Namespace
metadata:
  name: k8sproject
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: k8sproject
type: Opaque
data:
  aws-access-key-id: "XXXX_AWS_ACCESS_KEY_ID_XXXX"
  aws-secret-access-key: "XXXX_AWS_SECRET_ACCESS_KEY_XXXX"

